import { ReactNode } from 'react';
import { ReactQueryProvider } from './react-query-provider';
import './globals.css'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface LayoutProps {
  children?: ReactNode
}

 
export default function RootLayout({ children }: {children: React.ReactNode}) {
  return (
    <html>
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  )
}
